from django.urls import path
from . import kassa_views

urlpatterns = [
    path("", kassa_views.kassa_dashboard, name="kassa_dashboard"),
    path("export-excel/", kassa_views.kassa_dashboard_export_excel, name="kassa_dashboard_export_excel"),
    path("overview/", kassa_views.kassa_overview, name="kassa_overview"),
    path("overview/export/", kassa_views.kassa_overview_export, name="kassa_overview_export"),
    path("overview/export-excel/", kassa_views.kassa_overview_export_excel, name="kassa_overview_export_excel"),
    path("list/", kassa_views.kassa_list, name="kassa_list"),
    path("create/", kassa_views.kassa_create, name="kassa_create"),
    path("<int:pk>/", kassa_views.kassa_detail, name="kassa_detail"),
    path("<int:pk>/export-excel/", kassa_views.kassa_detail_export_excel, name="kassa_detail_export_excel"),
    path("<int:pk>/update/", kassa_views.kassa_update, name="kassa_update"),
    path("<int:pk>/delete/", kassa_views.kassa_delete, name="kassa_delete"),
    path("<int:pk>/income/", kassa_views.kassa_add_income, name="kassa_add_income"),
    path("<int:pk>/expense/", kassa_views.kassa_add_expense, name="kassa_add_expense"),
    path("<int:pk>/employee-payout/", kassa_views.kassa_add_employee_payout, name="kassa_add_employee_payout"),
    path("<int:pk>/employee-advance-close/", kassa_views.kassa_employee_advance_close, name="kassa_advance_close"),
    path("<int:pk>/transfer/", kassa_views.kassa_transfer, name="kassa_transfer"),
    path("history/", kassa_views.kassa_history, name="kassa_history"),
    path("register-payment/", kassa_views.kassa_register_payment, name="kassa_register_payment"),
    path("payment-methods/", kassa_views.payment_method_list, name="payment_method_list"),
    path("payment-methods/create/", kassa_views.payment_method_create, name="payment_method_create"),
    path("payment-methods/<int:pk>/edit/", kassa_views.payment_method_edit, name="payment_method_edit"),
    path("payment-methods/<int:pk>/toggle/", kassa_views.payment_method_toggle, name="payment_method_toggle"),
    path("payment-methods/<int:pk>/delete/", kassa_views.payment_method_delete, name="payment_method_delete"),
    path("expense-categories/", kassa_views.expense_category_list, name="expense_category_list"),
    path("expense-categories/create/", kassa_views.expense_category_create, name="expense_category_create"),
    path("expense-categories/<int:pk>/edit/", kassa_views.expense_category_edit, name="expense_category_edit"),
    path("expense-categories/<int:pk>/toggle/", kassa_views.expense_category_toggle, name="expense_category_toggle"),
    path("expense-categories/<int:pk>/delete/", kassa_views.expense_category_delete, name="expense_category_delete"),
    path("income-categories/", kassa_views.income_category_list, name="income_category_list"),
    path("income-categories/create/", kassa_views.income_category_create, name="income_category_create"),
    path("income-categories/<int:pk>/edit/", kassa_views.income_category_edit, name="income_category_edit"),
    path("income-categories/<int:pk>/toggle/", kassa_views.income_category_toggle, name="income_category_toggle"),
    path("income-categories/<int:pk>/delete/", kassa_views.income_category_delete, name="income_category_delete"),
]
