# Generated by Django 5.2.15 on 2026-06-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='MarketingSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="So'rovnoma turi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Marketing so'rovnoma",
                'verbose_name_plural': "Marketing so'rovnomalar",
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('kutilyotgan', 'Kutilyotgan')], default='aktiv', max_length=20, verbose_name='Guruh holati')),
                ('education_type', models.CharField(choices=[('onlayn', 'Onlayn'), ('oflayn', 'Oflayn')], default='oflayn', max_length=20, verbose_name="Ta'lim turi")),
                ('day_type', models.CharField(choices=[('toq', 'Toq kunlar'), ('juft', 'Juft kunlar'), ('har_kun', 'Har kunlik')], default='har_kun', max_length=20, verbose_name='Dars kunlari')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram guruh havolasi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='frontend.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('father_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ism familya')),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Otasining nomeri')),
                ('mother_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Onasining ism familya')),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Onasining nomeri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='frontend.group', verbose_name='Guruh')),
                ('marketing_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='frontend.marketingsurvey', verbose_name="Marketing so'rovnoma")),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
    ]
