# Generated by Django 5.2.15 on 2026-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kunlarni yozing'),
        ),
        migrations.AlterField(
            model_name='group',
            name='day_type',
            field=models.CharField(choices=[('toq', 'Toq kunlar'), ('juft', 'Juft kunlar'), ('har_kun', 'Har kunlik')], default='har_kun', max_length=20, verbose_name='Dars kunlari turi'),
        ),
    ]
