# Generated by Django 5.2.15 on 2026-06-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_group_days_alter_group_day_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='frozen_until',
            field=models.DateField(blank=True, null=True, verbose_name='Muzlatish tugash sanasi'),
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('joined', "Guruhga qo'shildi"), ('removed', 'Guruhdan chiqarildi'), ('frozen', 'Muzlatildi'), ('unfrozen', 'Muzlatish bekor qilindi')], max_length=20, verbose_name='Harakat')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='frontend.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi harakati",
                'verbose_name_plural': "O'quvchi harakatlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
