# Generated by Django 5.2.15 on 2026-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_student_frozen_until_studentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('kutilyotgan', 'Kutilyotgan'), ('chiqarilgan', 'Chiqarilgan')], default='kutilyotgan', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('kutilyotgan', 'Kutilyotgan'), ('yopilgan', 'Yopilgan')], default='aktiv', max_length=20, verbose_name='Guruh holati'),
        ),
    ]
