# Generated by Django 5.2.15 on 2026-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_lessontime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontime',
            options={'ordering': ['start_time'], 'verbose_name': 'Dars vaqti', 'verbose_name_plural': 'Dars vaqtlari'},
        ),
        migrations.RemoveField(
            model_name='lessontime',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='lessontime',
            name='days',
            field=models.CharField(default=1, max_length=255, verbose_name='Hafta kunlari'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('kutilyotgan', 'Kutilyotgan'), ('yopilgan', 'Yopilgan'), ('arxivlangan', 'Arxivlangan')], default='aktiv', max_length=20, verbose_name='Guruh holati'),
        ),
    ]
