# Generated by Django 5.2.15 on 2026-06-23 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_lessontime_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Rol nomi')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Daraja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta')),
                ('gender', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vazifasi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Profil rasmi')),
                ('salary_enabled', models.BooleanField(default=False, verbose_name='Ish haqi chiqarish')),
                ('salary_same', models.BooleanField(default=False, verbose_name='Hammaga bir xil')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ish haqi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(blank=True, to='frontend.branch', verbose_name='Filiallar')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
    ]
