# Generated by Django 5.2.15 on 2026-06-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_student_group_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduated_groups',
            field=models.ManyToManyField(blank=True, related_name='graduated_students', to='frontend.group', verbose_name='Bitirilgan guruhlar'),
        ),
    ]
