# Generated by Django 5.2.15 on 2026-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_student_graduated_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
    ]
