# Generated by Django 5.2.15 on 2026-06-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_group_end_date_alter_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='desired_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='frontend.course', verbose_name='Qiziqqan kursi'),
        ),
    ]
