# Generated by Django 5.2.15 on 2026-06-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sabab nomi')),
                ('reason_type', models.CharField(choices=[('absent', 'Kelmadi'), ('excused', 'Sababli kelmadi'), ('both', 'Ikkalasi')], default='both', max_length=10, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Davomat sababi',
                'verbose_name_plural': 'Davomat sabablari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Izoh'),
        ),
    ]
