# Generated by Django 5.2.15 on 2026-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_absencereason_attendance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('excused', 'Sababli kelmadi'), ('boshqoldi', 'Boshqoldi')], default='present', max_length=15, verbose_name='Holati'),
        ),
    ]
