# Generated by Django 5.2.15 on 2026-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan'),
        ),
    ]
