# Generated by Django 5.2.15 on 2026-06-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_verificationcode_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram chat ID'),
        ),
    ]
