# Generated by Django 5.2.15 on 2026-06-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_add_support_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('excused', 'Sababli kelmadi')], default='present', max_length=15, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='GroupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Harakat')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='frontend.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Guruh tarixi',
                'verbose_name_plural': 'Guruh tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
