# Generated by Django 5.2.15 on 2026-07-01 05:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_attendance_status_grouplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='1 dars narxi'),
        ),
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balans')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='frontend.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi balansi",
                'verbose_name_plural': "O'quvchi balanslari",
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Operatsiyadan keyingi balans')),
                ('transaction_type', models.CharField(choices=[('payment', "To'lov"), ('lesson', 'Dars uchun yechildi'), ('correction', 'Tuzatish')], max_length=20, verbose_name='Operatsiya turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='frontend.attendance', verbose_name='Davomat')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='frontend.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='frontend.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLessonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Shaxsiy dars narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lesson_prices', to='frontend.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_prices', to='frontend.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi shaxsiy narxi",
                'verbose_name_plural': "O'quvchi shaxsiy narxlari",
                'unique_together': {('student', 'group')},
            },
        ),
    ]
