# Generated by Django 5.2.15 on 2026-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_group_lesson_price_studentbalance_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deduct_absent',
            field=models.BooleanField(default=False, verbose_name='Sababsiz kelmaganlardan pul yechish'),
        ),
    ]
