# Generated by Django 5.2.15 on 2026-07-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_group_deduct_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deduct_excused',
            field=models.BooleanField(default=False, verbose_name='Sababli kelmaganlardan pul yechish'),
        ),
    ]
