# Generated by Django 5.2.15 on 2026-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_group_deduct_excused'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduct_absent', models.BooleanField(default=False, verbose_name='Sababsiz kelmaganlardan pul yechish')),
                ('deduct_excused', models.BooleanField(default=False, verbose_name='Sababli kelmaganlardan pul yechish')),
            ],
            options={
                'verbose_name': 'Global sozlama',
                'verbose_name_plural': 'Global sozlamalar',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='deduct_absent',
        ),
        migrations.RemoveField(
            model_name='group',
            name='deduct_excused',
        ),
    ]
