# Generated by Django 5.2.15 on 2026-07-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_globalconfig_remove_group_deduct_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
