# Generated by Django 5.2.15 on 2026-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_transaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template nomi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart')),
                ('width', models.CharField(choices=[('58mm', '58 mm'), ('80mm', '80 mm')], default='80mm', max_length=10, verbose_name='Eni')),
                ('height_mode', models.CharField(choices=[('auto', 'Avtomatik'), ('custom', 'Maxsus')], default='auto', max_length=10, verbose_name='Balandlik rejimi')),
                ('height', models.PositiveIntegerField(default=300, verbose_name='Balandlik (mm)')),
                ('paper_margin', models.PositiveIntegerField(default=0, verbose_name="Qog'oz cheti (mm)")),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Fon rangi')),
                ('print_dpi', models.PositiveIntegerField(default=203, verbose_name='Chop etish DPI')),
                ('thermal_mode', models.BooleanField(default=False, verbose_name='Termal printer rejimi')),
                ('black_white', models.BooleanField(default=True, verbose_name='Qora-oq rejim')),
                ('page_padding', models.PositiveIntegerField(default=10, verbose_name='Sahifa ichki cheti (px)')),
                ('components', models.JSONField(blank=True, default=list, verbose_name='Komponentlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chek shabloni',
                'verbose_name_plural': 'Chek shablonlari',
            },
        ),
    ]
