# Generated by Django 5.2.15 on 2026-07-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_receipttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='receipt_logos/', verbose_name='Logo')),
                ('academy_name', models.CharField(default='IT HOUSE ACADEMY', max_length=255, verbose_name='Markaz nomi')),
                ('tagline', models.CharField(default="SIFATLI TA'LIM MARKAZI", max_length=255, verbose_name='Tagline')),
                ('accent_color', models.CharField(default='#2001FF', max_length=7, verbose_name='Asosiy rang')),
                ('receipt_title', models.CharField(default="TO'LOV CHEKI", max_length=255, verbose_name='Chek sarlavhasi')),
                ('receipt_prefix', models.CharField(default='Chek #', max_length=50, verbose_name='Chek prefiksi')),
                ('receipt_format', models.CharField(default='000000', max_length=50, verbose_name='Chek formati')),
                ('footer_text', models.TextField(blank=True, default='Bizni tanlaganingiz uchun rahmat!', verbose_name='Footer matni')),
                ('thank_you_text', models.CharField(default='Rahmat!', max_length=255, verbose_name='Rahmat yozuvi')),
                ('payment_text', models.CharField(default="To'lov summasi", max_length=255, verbose_name="To'lov matni")),
                ('extra_notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('message_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xabar matni')),
                ('qr_link', models.URLField(blank=True, default='', verbose_name='QR Code havolasi')),
                ('auto_generate_qr', models.BooleanField(default=True, verbose_name='Avtomatik QR')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chek sozlamasi',
                'verbose_name_plural': 'Chek sozlamalari',
            },
        ),
    ]
