# Generated by Django 5.1.15 on 2026-07-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_receiptsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='paper_height',
            field=models.CharField(default='210mm', max_length=10, verbose_name="Qog'oz bo'yi"),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='paper_width',
            field=models.CharField(default='58mm', max_length=10, verbose_name="Qog'oz eni"),
        ),
    ]
