# Generated by Django 5.1.15 on 2026-07-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_receiptsettings_paper_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_html', models.TextField(verbose_name='Chek HTML')),
                ('settings_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar holati')),
                ('student_name', models.CharField(blank=True, default='', max_length=255, verbose_name="O'quvchi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_receipt', to='frontend.transaction', verbose_name='Tranzaksiya')),
            ],
            options={
                'verbose_name': 'Saqlangan chek',
                'verbose_name_plural': 'Saqlangan cheklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
