# Generated by Django 5.1.15 on 2026-07-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_savedreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='font_amount',
            field=models.CharField(default='22px', max_length=10, verbose_name='Summa shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_amount_label',
            field=models.CharField(default='10px', max_length=10, verbose_name="To'lov yozuvi shrifti"),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_balance',
            field=models.CharField(default='10px', max_length=10, verbose_name='Balans shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_contact',
            field=models.CharField(default='9px', max_length=10, verbose_name='Kontakt shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_footer',
            field=models.CharField(default='10px', max_length=10, verbose_name='Footer shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_name',
            field=models.CharField(default='18px', max_length=10, verbose_name='Markaz nomi shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_notes',
            field=models.CharField(default='10px', max_length=10, verbose_name='Izoh shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_row',
            field=models.CharField(default='10px', max_length=10, verbose_name='Qator shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_tagline',
            field=models.CharField(default='11px', max_length=10, verbose_name='Tagline shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_thanks',
            field=models.CharField(default='14px', max_length=10, verbose_name='Rahmat shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='font_title',
            field=models.CharField(default='14px', max_length=10, verbose_name='Sarlavha shrifti'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='paper_padding',
            field=models.CharField(default='2mm', max_length=10, verbose_name='Chek ichki cheti'),
        ),
    ]
