# Generated by Django 5.1 on 2026-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_receiptsettings_font_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', "To'lov"), ('lesson', 'Dars uchun yechildi'), ('correction', 'Tuzatish'), ('withdrawal', 'Pul qaytarish'), ('wrong', 'Xato amaliyot')], max_length=20, verbose_name='Operatsiya turi'),
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Daraja nomi')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Kunlik narx (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='frontend.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Kurs darajasi',
                'verbose_name_plural': 'Kurs darajalari',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='frontend.courselevel', verbose_name='Daraja'),
        ),
    ]
