# Generated by Django 5.1 on 2026-07-15 08:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_alter_transaction_transaction_type_courselevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kassa nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kassa', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
        migrations.CreateModel(
            name='KassaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', "To'lov"), ('income', 'Kirim'), ('expense', 'Chiqim'), ('transfer_in', "Kassa o'tkazma (kirish)"), ('transfer_out', "Kassa o'tkazma (chiqish)"), ('refund', 'Qaytarilgan pul')], max_length=20, verbose_name='Operatsiya turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Oldingi balans')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Yangi balans')),
                ('description', models.TextField(blank=True, default='', verbose_name='Sabab / Izoh')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name="To'lov usuli")),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_operations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='frontend.kassa', verbose_name='Kassa')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transactions', to='frontend.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Kassa tranzaksiyasi',
                'verbose_name_plural': 'Kassa tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KassaTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('description', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('from_kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='frontend.kassa', verbose_name='Yuboruvchi kassa')),
                ('to_kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='frontend.kassa', verbose_name='Qabul qiluvchi kassa')),
            ],
            options={
                'verbose_name': "Kassa o'tkazmasi",
                'verbose_name_plural': "Kassa o'tkazmalari",
                'ordering': ['-created_at'],
            },
        ),
    ]
