# Generated by Django 5.1 on 2026-07-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_kassa_kassatransaction_kassatransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kassa',
            name='kassa_type',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Plastik karta')], default='naqd', max_length=10, verbose_name='Kassa turi'),
        ),
        migrations.AlterField(
            model_name='kassa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kassalar', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
