# Generated by Django 5.1 on 2026-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_kassa_foreignkey_and_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="To'lov usuli nomi")),
                ('icon', models.CharField(default='fas fa-money-bill', max_length=50, verbose_name='Icon (FontAwesome)')),
                ('color', models.CharField(default='#059669', max_length=20, verbose_name='Rang (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'lov usuli",
                'verbose_name_plural': "To'lov usullari",
                'ordering': ['order', 'name'],
            },
        ),
    ]
