# Generated by Django 5.1 on 2026-07-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_seed_default_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kassa',
            name='kassa_type',
        ),
    ]
