# Generated by Django 5.1 on 2026-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_soft_delete_and_cascade_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassatransaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('arenda', 'Arenda'), ('maosh', 'Maosh'), ('kommunal', 'Kommunal'), ('kantselyariya', 'Kantselyariya'), ('boshqa', 'Boshqa')], default='', max_length=50, verbose_name='Chiqim kategoriyasi'),
        ),
    ]
