# Generated by Django 5.1 on 2026-07-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0043_expense_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='sms_signature',
            field=models.CharField(blank=True, default='IT House: 550552727', max_length=255, verbose_name='SMS imzosi (oxirida chiqadi)'),
        ),
    ]
