# Generated by Django 5.1 on 2026-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0044_receiptsettings_sms_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_icons/', verbose_name='Maxsus rasm'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(default='cash', max_length=50, verbose_name='Icon'),
        ),
    ]
