# Generated by Django 5.1 on 2026-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0046_incomecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassatransaction',
            name='income_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Kirim kategoriyasi'),
        ),
    ]
