# Generated by Django 5.1 on 2026-07-28 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0047_kassatransaction_income_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_type', models.CharField(choices=[('debt', 'Qarz eslatma'), ('absence', 'Davomat'), ('payment', "To'lov")], max_length=20, verbose_name='SMS turi')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Qabul qiluvchi')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('student_name', models.CharField(max_length=255, verbose_name="O'quvchi")),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('status', models.CharField(default='yuborildi', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuborgan')),
            ],
            options={
                'verbose_name': 'SMS tarixi',
                'verbose_name_plural': 'SMS tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
