# Generated by Django 5.1 on 2026-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_add_smshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='desired_course',
        ),
        migrations.AddField(
            model_name='student',
            name='desired_course',
            field=models.ManyToManyField(blank=True, related_name='interested_students', to='frontend.course', verbose_name='Qiziqqan kurslari'),
        ),
    ]
