# Generated by Django 5.1 on 2026-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_desired_course_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_language',
            field=models.CharField(blank=True, default="O'zbekcha", max_length=50, verbose_name="O'qitish tili"),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ish joyi'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True, null=True, verbose_name='Uy adresi'),
        ),
        migrations.AddField(
            model_name='student',
            name='lesson_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dars vaqti'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Onasining ish joyi'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name="To'lash sanasi"),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="O'qish joyi"),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="O'quvchi kategoriyasi"),
        ),
        migrations.AddField(
            model_name='student',
            name='target_university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maqsaddagi universitet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('kutilyotgan', 'Kutilyotgan'), ('bitirilgan', 'Bitirilgan'), ('chiqarilgan', 'Chiqarilgan')], default='kutilyotgan', max_length=20, verbose_name='Holati'),
        ),
    ]
