# Generated by Django 5.1 on 2026-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0050_add_student_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Davlat'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uy raqam'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_mfy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MFY'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='student',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ko'cha"),
        ),
    ]
