# Generated by Django 5.1 on 2026-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_student_address_country_student_address_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan'),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='action',
            field=models.CharField(choices=[('joined', "Guruhga qo'shildi"), ('removed', 'Guruhdan chiqarildi'), ('transferred', "Guruhdan ko'chirildi"), ('graduated', 'Guruhni bitirdi'), ('frozen', 'Muzlatildi'), ('unfrozen', 'Muzlatish bekor qilindi')], max_length=20, verbose_name='Harakat'),
        ),
    ]
