# Generated by Django 5.1 on 2026-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0052_studentlog_created_by_alter_studentlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='logo_height',
            field=models.CharField(default='60px', max_length=10, verbose_name='Logo balandligi'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='logo_width',
            field=models.CharField(default='160px', max_length=10, verbose_name='Logo kengligi'),
        ),
    ]
