# Generated by Django 5.1 on 2026-08-04 11:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0053_receiptsettings_logo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Foiz (%)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Oylik'), ('percent', 'Foiz')], default='percent', max_length=20, verbose_name='Oylik turi'),
        ),
        migrations.CreateModel(
            name='TeacherBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balans')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_balance', to='frontend.employee', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi balansi",
                'verbose_name_plural': "O'qituvchi balanslari",
            },
        ),
        migrations.CreateModel(
            name='TeacherTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Operatsiyadan keyingi balans')),
                ('transaction_type', models.CharField(choices=[('income', "To'lovdan tushum"), ('payout', 'Oylik berildi'), ('refund', "Qaytarilgan to'lov"), ('correction', 'Tuzatish')], max_length=20, verbose_name='Operatsiya turi')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Foiz (%)')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name="To'lov usuli")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_transactions', to='frontend.employee', verbose_name="O'qituvchi")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_transactions', to='frontend.group', verbose_name='Guruh')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_shares', to='frontend.transaction', verbose_name="To'lov tranzaksiyasi")),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_transactions', to='frontend.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi tranzaksiyasi",
                'verbose_name_plural': "O'qituvchi tranzaksiyalari",
                'ordering': ['-created_at'],
            },
        ),
    ]
