# Generated by Django 5.1 on 2026-08-06 12:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0054_employee_percent_employee_salary_type_teacherbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertransaction',
            name='salary_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oylik sanasi'),
        ),
        migrations.CreateModel(
            name='GroupTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='frontend.group', verbose_name='Guruh')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_assignments', to='frontend.employee', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Guruh o'qituvchi biriktiruvi",
                'verbose_name_plural': "Guruh o'qituvchi biriktiruvlari",
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonTeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('lesson_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Dars narxi')),
                ('teacher_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Foiz (%)')),
                ('teacher_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="O'qituvchi ulushi")),
                ('status', models.CharField(choices=[('pending', 'Kutilayotgan'), ('paid', "To'langan")], default='pending', max_length=15, verbose_name='Holati')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records', to='frontend.attendance', verbose_name='Davomat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_salaries', to='frontend.group', verbose_name='Guruh')),
                ('paid_by_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_salaries', to='frontend.transaction', verbose_name="To'lov tranzaksiyasi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_salaries', to='frontend.student', verbose_name="O'quvchi")),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_salaries', to='frontend.employee', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Dars o'qituvchi oyligi",
                'verbose_name_plural': "Dars o'qituvchi oyliklari",
                'ordering': ['date', 'id'],
            },
        ),
    ]
