# Generated by Django 5.1 on 2026-08-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_teachertransaction_salary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassatransaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassa_transactions', to='frontend.employee', verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='kassatransaction',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('salary', 'Xodimga oylik'), ('advance', 'Xodimga avans')], default='', max_length=20, verbose_name='Oylik / avans turi'),
        ),
        migrations.AddField(
            model_name='teachertransaction',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('salary', 'Xodimga oylik'), ('advance', 'Xodimga avans')], default='', max_length=20, verbose_name='Oylik / avans turi'),
        ),
    ]
