# Generated by Django 5.1 on 2026-08-08 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0056_kassatransaction_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherbalance',
            name='avans_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Avans qarzi'),
        ),
        migrations.AddField(
            model_name='teachertransaction',
            name='avans_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Operatsiyadan keyingi avans qarzi'),
        ),
        migrations.AlterField(
            model_name='teacherbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Oylik balansi'),
        ),
        migrations.AlterField(
            model_name='teachertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', "To'lovdan tushum"), ('payout', 'Oylik berildi'), ('advance', 'Avans berildi'), ('advance_close', 'Avans yopildi'), ('refund', "Qaytarilgan to'lov"), ('correction', 'Tuzatish')], max_length=20, verbose_name='Operatsiya turi'),
        ),
    ]
