# Generated by Django 5.1 on 2026-08-10 06:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0057_teacherbalance_avans_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Administrator/Support uchun tayinlangan oylik maosh (foiz tizimidan alohida)', max_digits=12, verbose_name='Belgilangan oylik maosh'),
        ),
    ]
