# Generated by Django 5.1 on 2026-08-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0058_employee_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='deduct_present',
            field=models.BooleanField(default=True, verbose_name='Keldi — pul yechish'),
        ),
    ]
