# Generated by Django 5.0.14 on 2026-08-27 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0059_globalconfig_deduct_present'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Kod nomi')),
                ('module', models.CharField(max_length=100, verbose_name='Modul')),
                ('action', models.CharField(max_length=100, verbose_name='Harakat')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruxsat',
                'verbose_name_plural': 'Ruxsatlar',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_codename', models.CharField(max_length=100, verbose_name='Ruxsat kodi')),
                ('permission_module', models.CharField(blank=True, default='', max_length=100, verbose_name='Modul')),
                ('action', models.CharField(choices=[('grant', 'Berildi'), ('revoke', 'Olib tashlandi')], max_length=20, verbose_name='Harakat')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_done', to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi")),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_received', to=settings.AUTH_USER_MODEL, verbose_name="Kimning huquqi o'zgartirildi")),
            ],
            options={
                'verbose_name': 'Ruxsat audit logi',
                'verbose_name_plural': 'Ruxsat audit loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan berilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_grants', to='frontend.permission', verbose_name='Ruxsat')),
            ],
            options={
                'verbose_name': 'Admin ruxsati',
                'verbose_name_plural': 'Admin ruxsatlari',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
