# Generated by Django 5.0.14 on 2026-08-28 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0060_permission_permissionauditlog_adminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram chat ID'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topshiriq nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name="Batafsil ma'lumot")),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('bajarildi', 'Bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='yangi', max_length=20, verbose_name='Holati')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='frontend.employee', verbose_name='Tayinlangan xodim')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
