# Generated by Django 5.0.14 on 2026-08-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0061_employee_telegram_chat_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.TextField(blank=True, default='', verbose_name='Eslatma'),
        ),
    ]
