# Generated by Django 5.0.14 on 2026-08-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('bajarildi', 'Bajarildi'), ('bajarilmadi', 'Bajarilmadi'), ('bekor_qilindi', 'Bekor qilindi')], default='yangi', max_length=20, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Eslatma matni')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('created_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Kim tomonidan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='frontend.employee', verbose_name='Tayinlangan xodim')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
