# Generated by Django 5.0.14 on 2026-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0064_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bildirishnomalarni ko'rgan vaqt"),
        ),
    ]
