# Generated by Django 5.0.14 on 2026-08-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0065_employee_notifications_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_eslatma_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eslatma bot chat ID'),
        ),
    ]
