# Generated by Django 5.0.14 on 2026-08-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0066_employee_telegram_eslatma_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EslatmaReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Davomat eslatmasi yoqilgan')),
                ('delay_minutes', models.PositiveIntegerField(default=60, verbose_name='Necha daqiqadan keyin eslatish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Davomat eslatmasi sozlamasi',
                'verbose_name_plural': 'Davomat eslatmasi sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='reminder',
            name='send_to_all',
            field=models.BooleanField(default=False, verbose_name='Barchaga yuborilgan'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='frontend.employee', verbose_name='Tayinlangan xodim'),
        ),
        migrations.CreateModel(
            name='AttendanceReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminder_logs', to='frontend.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Davomat eslatma logi',
                'verbose_name_plural': 'Davomat eslatma loglari',
                'unique_together': {('group', 'date')},
            },
        ),
    ]
