# Generated by Django 5.0.14 on 2026-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0067_attendance_reminder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(choices=[('muhim', '🔴 Muhim'), ('eslatma', '🟡 Eslatma'), ("ma'lumot", "🔵 Ma'lumot")], default='eslatma', max_length=20, verbose_name='Muhimlik'),
        ),
    ]
