# Generated by Django 5.0.14 on 2026-08-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0068_reminder_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_read_states', to='frontend.employee', verbose_name='Xodim')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='frontend.reminder', verbose_name='Eslatma')),
            ],
            options={
                'verbose_name': "Eslatmaning o'qilgan holati",
                'verbose_name_plural': "Eslatmalarning o'qilgan holati",
                'unique_together': {('reminder', 'employee')},
            },
        ),
    ]
