# Generated by Django 5.0.14 on 2026-08-28 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user(apps, schema_editor):
    """Eski qatorlarda user'ni employee.user'dan to'ldir — aks holda usbu
    foydalanuvchilar uchun eslatmalar yana o'qilmagan bo'lib ko'rinadi."""
    ReminderRead = apps.get_model('frontend', 'ReminderRead')
    for row in ReminderRead.objects.select_related('employee').filter(user__isnull=True, employee__user__isnull=False):
        row.user_id = row.employee.user_id
        row.save(update_fields=['user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0069_reminder_read_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reminderread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reminderread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_read_states', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='reminderread',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_read_states', to='frontend.employee', verbose_name='Xodim'),
        ),
        migrations.RunPython(backfill_user, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reminderread',
            constraint=models.UniqueConstraint(fields=('reminder', 'user'), name='uniq_reminder_user'),
        ),
        migrations.AddConstraint(
            model_name='reminderread',
            constraint=models.UniqueConstraint(fields=('reminder', 'employee'), name='uniq_reminder_employee'),
        ),
    ]
