# Generated by Django 5.0.14 on 2026-08-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0070_reminder_read_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='sms_type',
            field=models.CharField(choices=[('debt', 'Qarz eslatma'), ('absence', 'Davomat'), ('payment', "To'lov"), ('attendance', 'Davomat eslatmasi')], max_length=20, verbose_name='SMS turi'),
        ),
    ]
