# Generated by Django 5.0.14 on 2026-08-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0071_alter_smshistory_sms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='sms_type',
            field=models.CharField(choices=[('debt', 'Qarz eslatma'), ('absence', 'Davomat'), ('payment', "To'lov")], max_length=20, verbose_name='SMS turi'),
        ),
    ]
